In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [2]:
df=pd.read_csv("trial.csv",index_col=0)

In [3]:
df.reset_index(drop=True, inplace=True)

In [4]:
df.head()

PassengerId  Survived  Pclass  Sex  SibSp  Parch     Fare  Embarked  Age
0            1         0       3    1      1      0   7.2500         2   22
1            2         1       1    0      1      0  71.2833         0   38
2            3         1       3    0      0      0   7.9250         2   26
3            4         1       1    0      1      0  53.1000         2   35
4            5         0       3    1      0      0   8.0500         2   35

# Data Cleaning

In [5]:
#df.isnull().sum()

In [6]:
#df.isna().mean()

In [7]:
# We will fill the missing values of age by random sample imputation


In [8]:
#def randimp(df,variable):
    #df[variable+"_random"]=df[variable]
    #ran=df[variable].dropna().sample(df[variable].isnull().sum(),random_state=0)
    #ran.index=df[df[variable].isnull()].index
    #df.loc[df[variable].isnull(),variable+"_random"]=ran

In [9]:
#randimp(df,"Age")

In [10]:
df.head()

PassengerId  Survived  Pclass  Sex  SibSp  Parch     Fare  Embarked  Age
0            1         0       3    1      1      0   7.2500         2   22
1            2         1       1    0      1      0  71.2833         0   38
2            3         1       3    0      0      0   7.9250         2   26
3            4         1       1    0      1      0  53.1000         2   35
4            5         0       3    1      0      0   8.0500         2   35

In [11]:
#df=df.drop("Age",axis=1)
#df.head()

In [12]:
#df.isnull().sum()

In [13]:
#df["Embarked"].value_counts()

In [14]:
#df["Embarked"]=df["Embarked"].fillna("S")

In [15]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Sex            0
SibSp          0
Parch          0
Fare           0
Embarked       0
Age            0
dtype: int64

In [16]:
#df.head()

In [17]:
#df["Sex"]=pd.get_dummies(df["Sex"],drop_first=True)

In [18]:
#df.head()

In [19]:
#emp={"S":2,"Q":1,"C":0}
#df["Embarked"]=df["Embarked"].map(emp)

In [20]:
df.head()

PassengerId  Survived  Pclass  Sex  SibSp  Parch     Fare  Embarked  Age
0            1         0       3    1      1      0   7.2500         2   22
1            2         1       1    0      1      0  71.2833         0   38
2            3         1       3    0      0      0   7.9250         2   26
3            4         1       1    0      1      0  53.1000         2   35
4            5         0       3    1      0      0   8.0500         2   35

In [21]:
#df["Age"]=df["Age_random"].astype(int)


In [22]:
#df=df.drop("Age_random",axis=1)

In [23]:
df.head()

PassengerId  Survived  Pclass  Sex  SibSp  Parch     Fare  Embarked  Age
0            1         0       3    1      1      0   7.2500         2   22
1            2         1       1    0      1      0  71.2833         0   38
2            3         1       3    0      0      0   7.9250         2   26
3            4         1       1    0      1      0  53.1000         2   35
4            5         0       3    1      0      0   8.0500         2   35

In [24]:
df.shape

(891, 9)

In [25]:
#df.to_csv("trial.csv")

In [26]:
train=df[:691].copy()

test=df[691:].copy()

In [27]:
train.head()

PassengerId  Survived  Pclass  Sex  SibSp  Parch     Fare  Embarked  Age
0            1         0       3    1      1      0   7.2500         2   22
1            2         1       1    0      1      0  71.2833         0   38
2            3         1       3    0      0      0   7.9250         2   26
3            4         1       1    0      1      0  53.1000         2   35
4            5         0       3    1      0      0   8.0500         2   35

In [28]:
train.shape

(691, 9)

In [29]:
#train=org[:401].copy()

In [30]:
train.head()

PassengerId  Survived  Pclass  Sex  SibSp  Parch     Fare  Embarked  Age
0            1         0       3    1      1      0   7.2500         2   22
1            2         1       1    0      1      0  71.2833         0   38
2            3         1       3    0      0      0   7.9250         2   26
3            4         1       1    0      1      0  53.1000         2   35
4            5         0       3    1      0      0   8.0500         2   35

In [31]:
#test=org[401:].copy()

In [32]:
test.head()

PassengerId  Survived  Pclass  Sex  SibSp  Parch     Fare  Embarked  Age
691          692         1       3    0      0      1  13.4167         0    4
692          693         1       3    1      0      0  56.4958         2   36
693          694         0       3    1      0      0   7.2250         0   25
694          695         0       1    1      0      0  26.5500         2   60
695          696         0       2    1      0      0  13.5000         2   52

In [33]:
test.shape

(200, 9)

In [34]:
#from sklearn.model_selection import train_test_split


In [35]:
features=["Pclass","Sex","SibSp","Parch","Fare","Embarked","Age"]

In [36]:
X_train=train.loc[:,features]
X_test = test.loc[:,features]
y_train=train.loc[:,["Survived"]] #class label
y_test = test.loc[:,["Survived"]]

In [37]:
#X_train, X_test, y_train, y_test= train_test_split(X,y,random_state=0,train_size=0.6)

In [38]:
#org.shape

In [39]:
y_train.shape

(691, 1)

In [40]:
y_test.shape

(200, 1)

In [41]:
X_test.shape

(200, 7)

In [42]:
X_train.shape

(691, 7)

In [43]:
from sklearn.naive_bayes import BernoulliNB

In [44]:
bn = BernoulliNB()
bn.fit(X_train, y_train.values.ravel()) #  fitting bnb to the training set
y_pred=bn.predict(X_test) # predicting the test set


In [45]:
from sklearn.metrics import r2_score
from sklearn.metrics import accuracy_score

In [46]:
score=r2_score(y_test,y_pred)
accuracy=accuracy_score(y_test,y_pred)

In [47]:
score

0.141999141999142

In [48]:
accuracy

0.8

In [49]:
original_pred=y_pred
original_pred

array([1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 0], dtype=int64)

In [50]:
original_test=y_test
original_test

Survived
691         1
692         1
693         0
694         0
695         0
..        ...
886         0
887         1
888         0
889         1
890         0

[200 rows x 1 columns]

In [51]:
original_test.index

RangeIndex(start=691, stop=891, step=1)

# Metamorphic Testing

# MR 1.2 Permutation of the attribute


In [52]:
feature=["SibSp","Pclass","Sex","Fare","Parch","Age","Embarked"]

In [53]:
#org.head()

In [54]:
X_train=train.loc[:,feature]
X_test = test.loc[:,feature]
y_train=train.loc[:,["Survived"]] #class label
y_test = test.loc[:,["Survived"]]

In [55]:
#X_train, X_test, y_train, y_test= train_test_split(X,y,random_state=0,train_size=0.6)

In [56]:
bn = BernoulliNB()
bn.fit(X_train, y_train.values.ravel()) #  fitting bnb to the training set
y_pred=bn.predict(X_test)

In [57]:
y_pred

array([1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 0], dtype=int64)

In [58]:
y_test

Survived
691         1
692         1
693         0
694         0
695         0
..        ...
886         0
887         1
888         0
889         1
890         0

[200 rows x 1 columns]

In [59]:
new_accuracy = accuracy_score(y_test,y_pred)

In [60]:
new_accuracy

0.8

In [61]:
# When permutation of attributes and test set are done, the accuracy is almost same as original

In [62]:
y_pred[0]==original_pred[0]

True

In [63]:
ones=0
zeros=0
other=0
for x in range(0,200):
    
    if original_pred[x]==1 and y_pred[x]==1:
        ones+=1
    elif original_pred[x]==0 and y_pred[x]==0:
        zeros+=1
    else:
        other+=1
print(ones,zeros,other)

66 134 0


In [64]:
ones=0
zeros=0
for x in range(len(original_pred)):
    if original_pred[x]==1:
        ones+=1
    else:
        zeros+=1
print(ones,zeros)

66 134


# MR 2.1 Addition of uninformative Attribute 

# in this case we consider passenger ID as an uninformative attrib 

adding a new column with same numbers ie equalyy associated with all the classes.

In [65]:
#org.head()

In [66]:
orga=df.copy()

In [67]:
orga["uninf"]=3

In [68]:
orga.head()

PassengerId  Survived  Pclass  Sex  SibSp  Parch     Fare  Embarked  Age  \
0            1         0       3    1      1      0   7.2500         2   22   
1            2         1       1    0      1      0  71.2833         0   38   
2            3         1       3    0      0      0   7.9250         2   26   
3            4         1       1    0      1      0  53.1000         2   35   
4            5         0       3    1      0      0   8.0500         2   35   

   uninf  
0      3  
1      3  
2      3  
3      3  
4      3

In [69]:
feature=["Pclass","Sex","SibSp","Parch","Fare","Embarked","Age","uninf"]

In [70]:
train = orga[:691].copy()

In [71]:
test = orga[691:].copy()

In [72]:
X_train=train.loc[:,feature]
X_test = test.loc[:,feature]
y_train=train.loc[:,["Survived"]] #class label
y_test = test.loc[:,["Survived"]]

In [73]:
#X_train, X_test, y_train, y_test= train_test_split(X,y,random_state=0,train_size=0.6)

In [74]:
bn = BernoulliNB()
bn.fit(X_train, y_train.values.ravel()) #  fitting bnb to the training set
y_pred=bn.predict(X_test)

In [75]:
y_pred

array([1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 0], dtype=int64)

In [76]:
y_test

Survived
691         1
692         1
693         0
694         0
695         0
..        ...
886         0
887         1
888         0
889         1
890         0

[200 rows x 1 columns]

In [77]:
# The new accuracy is almost similar to the original one

In [78]:
accuracy_score(y_test,y_pred)

0.8

In [79]:
y_pred[0]==original_pred[0]

True

In [80]:
oness=0
zeross=0
for x in range(len(original_pred)):
    if original_pred[x]==1:
        oness+=1
    else:
        zeross+=1
print(oness,zeross)

66 134


In [81]:
ones=0
zeros=0
other=0
for x in range(0,200):
    
    if original_pred[x]==1 and y_pred[x]==1:
        ones+=1
    elif original_pred[x]==0 and y_pred[x]==0:
        zeros+=1
    else:
        other+=1
print(ones,zeros,other)

66 134 0


# MR 2.2 Addition of informative Attributes

add a new column in such a way that if survived =1 its value should be the same for others ie survived =0 that value can be anything

In [82]:
chn=df.copy()

In [83]:
chn.head()

PassengerId  Survived  Pclass  Sex  SibSp  Parch     Fare  Embarked  Age
0            1         0       3    1      1      0   7.2500         2   22
1            2         1       1    0      1      0  71.2833         0   38
2            3         1       3    0      0      0   7.9250         2   26
3            4         1       1    0      1      0  53.1000         2   35
4            5         0       3    1      0      0   8.0500         2   35

In [84]:
chn.loc[chn["Survived"]==1,"info"]=1

In [85]:
chn.head()

PassengerId  Survived  Pclass  Sex  SibSp  Parch     Fare  Embarked  Age  \
0            1         0       3    1      1      0   7.2500         2   22   
1            2         1       1    0      1      0  71.2833         0   38   
2            3         1       3    0      0      0   7.9250         2   26   
3            4         1       1    0      1      0  53.1000         2   35   
4            5         0       3    1      0      0   8.0500         2   35   

   info  
0   NaN  
1   1.0  
2   1.0  
3   1.0  
4   NaN

In [86]:
chn.loc[chn["Survived"]==0,"info"]=np.random.randint(2,10,size=549)

In [87]:
chn.head()

PassengerId  Survived  Pclass  Sex  SibSp  Parch     Fare  Embarked  Age  \
0            1         0       3    1      1      0   7.2500         2   22   
1            2         1       1    0      1      0  71.2833         0   38   
2            3         1       3    0      0      0   7.9250         2   26   
3            4         1       1    0      1      0  53.1000         2   35   
4            5         0       3    1      0      0   8.0500         2   35   

   info  
0   4.0  
1   1.0  
2   1.0  
3   1.0  
4   6.0

In [88]:
feature=["Pclass","Sex","SibSp","Parch","Fare","Embarked","Age","info"]

In [89]:
train = chn[:691].copy()

In [90]:
test = chn[691:].copy()

In [91]:
X_train=train.loc[:,feature]
X_test = test.loc[:,feature]
y_train=train.loc[:,["Survived"]] #class label
y_test = test.loc[:,["Survived"]]

In [92]:
#X_train, X_test, y_train, y_test= train_test_split(X,y,random_state=0,train_size=0.6)

In [93]:
bn = BernoulliNB()
bn.fit(X_train, y_train.values.ravel()) #  fitting bnb to the training set
y_pred=bn.predict(X_test)

In [94]:
y_pred

array([1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 0], dtype=int64)

In [95]:
y_test

Survived
691         1
692         1
693         0
694         0
695         0
..        ...
886         0
887         1
888         0
889         1
890         0

[200 rows x 1 columns]

In [96]:
accuracy_score(y_test,y_pred)

0.8

In [97]:
y_pred[0]==original_pred[0]

True

In [98]:
ones=0
zeros=0
other=0
for x in range(0,200):
    
    if original_pred[x]==1 and y_pred[x]==1:
        ones+=1
    elif original_pred[x]==0 and y_pred[x]==0:
        zeros+=1
    else:
        other+=1
print(ones,zeros,other)

66 134 0


In [99]:
oness=0
zeross=0
for x in range(len(original_pred)):
    if original_pred[x]==1:
        oness+=1
    else:
        zeross+=1
print(oness,zeross)


66 134


In [100]:
print(f"The number of ones that have changed to zeros are {oness-ones}")
# print(f"The number of zeros that have changed to ones are {zeross-zeros}")


The number of ones that have changed to zeros are 0


In [101]:
y_pred.shape

(200,)

In [102]:
original_pred.shape

(200,)

# Repeat this test again and check it for zero's

In [103]:
chi = df.copy()

In [104]:
chi.head()

PassengerId  Survived  Pclass  Sex  SibSp  Parch     Fare  Embarked  Age
0            1         0       3    1      1      0   7.2500         2   22
1            2         1       1    0      1      0  71.2833         0   38
2            3         1       3    0      0      0   7.9250         2   26
3            4         1       1    0      1      0  53.1000         2   35
4            5         0       3    1      0      0   8.0500         2   35

In [105]:
chi.loc[chn["Survived"]==0,"info"]=1

In [106]:
chi.head()

PassengerId  Survived  Pclass  Sex  SibSp  Parch     Fare  Embarked  Age  \
0            1         0       3    1      1      0   7.2500         2   22   
1            2         1       1    0      1      0  71.2833         0   38   
2            3         1       3    0      0      0   7.9250         2   26   
3            4         1       1    0      1      0  53.1000         2   35   
4            5         0       3    1      0      0   8.0500         2   35   

   info  
0   1.0  
1   NaN  
2   NaN  
3   NaN  
4   1.0

In [107]:
chi[chi["Survived"]==1]

PassengerId  Survived  Pclass  Sex  SibSp  Parch     Fare  Embarked  Age  \
1              2         1       1    0      1      0  71.2833         0   38   
2              3         1       3    0      0      0   7.9250         2   26   
3              4         1       1    0      1      0  53.1000         2   35   
8              9         1       3    0      0      2  11.1333         2   27   
9             10         1       2    0      1      0  30.0708         0   14   
..           ...       ...     ...  ...    ...    ...      ...       ...  ...   
875          876         1       3    0      0      0   7.2250         0   15   
879          880         1       1    0      0      1  83.1583         0   56   
880          881         1       2    0      0      1  26.0000         2   25   
887          888         1       1    0      0      0  30.0000         2   19   
889          890         1       1    1      0      0  30.0000         0   26   

     info  
1     NaN  
2     NaN  
3     NaN  
8     NaN  
9     NaN  
..    ...  
875   NaN  
879   NaN  
880   NaN  
887   NaN  
889   NaN  

[342 rows x 10 columns]

In [108]:
chi[chi["Survived"]==0]

PassengerId  Survived  Pclass  Sex  SibSp  Parch     Fare  Embarked  Age  \
0              1         0       3    1      1      0   7.2500         2   22   
4              5         0       3    1      0      0   8.0500         2   35   
5              6         0       3    1      0      0   8.4583         1   28   
6              7         0       1    1      0      0  51.8625         2   54   
7              8         0       3    1      3      1  21.0750         2    2   
..           ...       ...     ...  ...    ...    ...      ...       ...  ...   
884          885         0       3    1      0      0   7.0500         2   25   
885          886         0       3    0      0      5  29.1250         1   39   
886          887         0       2    1      0      0  13.0000         2   27   
888          889         0       3    0      1      2  23.4500         2   15   
890          891         0       3    1      0      0   7.7500         1   32   

     info  
0     1.0  
4     1.0  
5     1.0  
6     1.0  
7     1.0  
..    ...  
884   1.0  
885   1.0  
886   1.0  
888   1.0  
890   1.0  

[549 rows x 10 columns]

In [109]:
chi.loc[chi["Survived"]==1,"info"]=np.random.randint(2,10,size=342)

In [110]:
chi.head()

PassengerId  Survived  Pclass  Sex  SibSp  Parch     Fare  Embarked  Age  \
0            1         0       3    1      1      0   7.2500         2   22   
1            2         1       1    0      1      0  71.2833         0   38   
2            3         1       3    0      0      0   7.9250         2   26   
3            4         1       1    0      1      0  53.1000         2   35   
4            5         0       3    1      0      0   8.0500         2   35   

   info  
0   1.0  
1   5.0  
2   2.0  
3   3.0  
4   1.0

In [111]:
chi.tail()

PassengerId  Survived  Pclass  Sex  SibSp  Parch   Fare  Embarked  Age  \
886          887         0       2    1      0      0  13.00         2   27   
887          888         1       1    0      0      0  30.00         2   19   
888          889         0       3    0      1      2  23.45         2   15   
889          890         1       1    1      0      0  30.00         0   26   
890          891         0       3    1      0      0   7.75         1   32   

     info  
886   1.0  
887   9.0  
888   1.0  
889   3.0  
890   1.0

In [112]:
feature=["Pclass","Sex","SibSp","Parch","Fare","Embarked","Age","info"]

In [113]:
test = chi[691:].copy()
train = chi[:691].copy()

In [114]:
X_train=train.loc[:,feature]
X_test = test.loc[:,feature]
y_train=train.loc[:,["Survived"]] #class label
y_test = test.loc[:,["Survived"]]

In [115]:
bn = BernoulliNB()
bn.fit(X_train, y_train.values.ravel()) #  fitting bnb to the training set
y_pred=bn.predict(X_test)

In [116]:
y_pred

array([1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 0], dtype=int64)

In [117]:
ones=0
zeros=0
other=0
for x in range(0,200):
    
    if original_pred[x]==1 and y_pred[x]==1:
        ones+=1
    elif original_pred[x]==0 and y_pred[x]==0:
        zeros+=1
    else:
        other+=1
print(ones,zeros,other)

66 134 0


In [118]:

oness=0
zeross=0
for x in range(len(original_pred)):
    if original_pred[x]==1:
        oness+=1
    else:
        zeross+=1
print(oness,zeross)


66 134


In [119]:
#print(f"The number of ones that have changed to zeros are {oness-ones}")
print(f"The number of zeros that have changed to ones are {zeross-zeros}")

The number of zeros that have changed to ones are 0


# MR 3.2 Additional training sample
# We need to duplicate one class label ie either 0 or 1 and we must check the predictions of a required label

# should be only done training data set not on testing 

In [120]:
df.copy()

PassengerId  Survived  Pclass  Sex  SibSp  Parch     Fare  Embarked  Age
0              1         0       3    1      1      0   7.2500         2   22
1              2         1       1    0      1      0  71.2833         0   38
2              3         1       3    0      0      0   7.9250         2   26
3              4         1       1    0      1      0  53.1000         2   35
4              5         0       3    1      0      0   8.0500         2   35
..           ...       ...     ...  ...    ...    ...      ...       ...  ...
886          887         0       2    1      0      0  13.0000         2   27
887          888         1       1    0      0      0  30.0000         2   19
888          889         0       3    0      1      2  23.4500         2   15
889          890         1       1    1      0      0  30.0000         0   26
890          891         0       3    1      0      0   7.7500         1   32

[891 rows x 9 columns]

In [121]:
train=df[:691].copy()
test = df[691:].copy()

In [122]:
zer=train.copy()
zer.shape

(691, 9)

In [123]:
rep=zer[zer["Survived"]==1]
rep

PassengerId  Survived  Pclass  Sex  SibSp  Parch      Fare  Embarked  Age
1              2         1       1    0      1      0   71.2833         0   38
2              3         1       3    0      0      0    7.9250         2   26
3              4         1       1    0      1      0   53.1000         2   35
8              9         1       3    0      0      2   11.1333         2   27
9             10         1       2    0      1      0   30.0708         0   14
..           ...       ...     ...  ...    ...    ...       ...       ...  ...
677          678         1       3    0      0      0    9.8417         2   18
679          680         1       1    1      0      1  512.3292         0   36
681          682         1       1    1      0      0   76.7292         0   27
689          690         1       1    0      0      1  211.3375         2   15
690          691         1       1    1      1      0   57.0000         2   31

[268 rows x 9 columns]

In [124]:
sa=pd.concat([zer,rep],axis=0)

In [125]:
sa.shape

(959, 9)

In [126]:
feature=["Pclass","Sex","SibSp","Parch","Fare","Embarked","Age"]

In [127]:
X_train=sa.loc[:,feature]
X_test = test.loc[:,feature]
y_train=sa.loc[:,["Survived"]] #class label
y_test = test.loc[:,["Survived"]]

In [128]:
#X_train, X_test, y_train, y_test= train_test_split(X,y,random_state=0,train_size=0.6)

In [129]:
bn = BernoulliNB()
bn.fit(X_train, y_train.values.ravel()) #  fitting bnb to the training set
y_pred=bn.predict(X_test)

In [130]:
y_pred

array([1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 0], dtype=int64)

In [131]:
y_test.index

RangeIndex(start=691, stop=891, step=1)

In [132]:
original_pred

array([1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 0], dtype=int64)

In [133]:
original_test.index

RangeIndex(start=691, stop=891, step=1)

In [134]:
original_pred.shape

(200,)

In [135]:
y_pred.shape

(200,)

In [136]:
ones=0
zeros=0
other=0
for x in range(0,200):
    
    if original_pred[x]==1 and y_pred[x]==1:
        ones+=1
    elif original_pred[x]==0 and y_pred[x]==0:
        zeros+=1
    else:
        other+=1
print(ones,zeros,other)

66 128 6


In [137]:
oness=0
zeross=0
for x in range(len(original_pred)):
    if original_pred[x]==1:
        oness+=1
    else:
        zeross+=1
print(oness,zeross)

66 134


In [138]:
print(f"The number of ones that have changed to zeros are {oness-ones}")
#print(f"The number of zeros that have changed to ones are {zeross-zeros}")


The number of ones that have changed to zeros are 0


# Repeating this test and checking for zeros

In [139]:
train=df[:691].copy()
test = df[691:].copy()

In [140]:
zer=train.copy()
zer.shape

(691, 9)

In [141]:
rep=zer[zer["Survived"]==0]
rep

PassengerId  Survived  Pclass  Sex  SibSp  Parch     Fare  Embarked  Age
0              1         0       3    1      1      0   7.2500         2   22
4              5         0       3    1      0      0   8.0500         2   35
5              6         0       3    1      0      0   8.4583         1   28
6              7         0       1    1      0      0  51.8625         2   54
7              8         0       3    1      3      1  21.0750         2    2
..           ...       ...     ...  ...    ...    ...      ...       ...  ...
684          685         0       2    1      1      1  39.0000         2   60
685          686         0       2    1      1      2  41.5792         0   25
686          687         0       3    1      4      1  39.6875         2   14
687          688         0       3    1      0      0  10.1708         2   19
688          689         0       3    1      0      0   7.7958         2   18

[423 rows x 9 columns]

In [142]:
sa=pd.concat([zer,rep],axis=0)

In [143]:
sa.shape

(1114, 9)

In [144]:
feature=["Pclass","Sex","SibSp","Parch","Fare","Embarked","Age"]

In [145]:
X_train=sa.loc[:,feature]
X_test = test.loc[:,feature]
y_train=sa.loc[:,["Survived"]] #class label
y_test = test.loc[:,["Survived"]]

In [146]:
bn = BernoulliNB()
bn.fit(X_train, y_train.values.ravel()) #  fitting bnb to the training set
y_pred=bn.predict(X_test)

In [147]:
y_pred

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0], dtype=int64)

In [148]:
original_pred

array([1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 0], dtype=int64)

In [149]:
ones=0
zeros=0
other=0
for x in range(0,200):
    
    if original_pred[x]==1 and y_pred[x]==1:
        ones+=1
    elif original_pred[x]==0 and y_pred[x]==0:
        zeros+=1
    else:
        other+=1
print(ones,zeros,other)

44 134 22


In [150]:
oness=0
zeross=0
for x in range(len(original_pred)):
    if original_pred[x]==1:
        oness+=1
    else:
        zeross+=1
print(oness,zeross)

66 134


In [151]:
#print(f"The number of ones that have changed to zeros are {oness-ones}")
print(f"The number of zeros that have changed to ones are {zeross-zeros}")

The number of zeros that have changed to ones are 0


# MR 1.1 Permutation of class labels

In [152]:
df.head()

PassengerId  Survived  Pclass  Sex  SibSp  Parch     Fare  Embarked  Age
0            1         0       3    1      1      0   7.2500         2   22
1            2         1       1    0      1      0  71.2833         0   38
2            3         1       3    0      0      0   7.9250         2   26
3            4         1       1    0      1      0  53.1000         2   35
4            5         0       3    1      0      0   8.0500         2   35

In [153]:
org1=df.copy()

In [154]:
train=org1[:691].copy()

In [155]:
train.head()

PassengerId  Survived  Pclass  Sex  SibSp  Parch     Fare  Embarked  Age
0            1         0       3    1      1      0   7.2500         2   22
1            2         1       1    0      1      0  71.2833         0   38
2            3         1       3    0      0      0   7.9250         2   26
3            4         1       1    0      1      0  53.1000         2   35
4            5         0       3    1      0      0   8.0500         2   35

In [156]:
test=org1[691:].copy()

In [157]:
test.head()

PassengerId  Survived  Pclass  Sex  SibSp  Parch     Fare  Embarked  Age
691          692         1       3    0      0      1  13.4167         0    4
692          693         1       3    1      0      0  56.4958         2   36
693          694         0       3    1      0      0   7.2250         0   25
694          695         0       1    1      0      0  26.5500         2   60
695          696         0       2    1      0      0  13.5000         2   52

In [158]:
org1.shape

(891, 9)

In [159]:
train.loc[train["Survived"]==1,"Survived"]= "one"

In [160]:
train.head()

PassengerId Survived  Pclass  Sex  SibSp  Parch     Fare  Embarked  Age
0            1        0       3    1      1      0   7.2500         2   22
1            2      one       1    0      1      0  71.2833         0   38
2            3      one       3    0      0      0   7.9250         2   26
3            4      one       1    0      1      0  53.1000         2   35
4            5        0       3    1      0      0   8.0500         2   35

In [161]:
train.loc[train["Survived"]==0,"Survived"]= 1

In [162]:
train.head()

PassengerId Survived  Pclass  Sex  SibSp  Parch     Fare  Embarked  Age
0            1        1       3    1      1      0   7.2500         2   22
1            2      one       1    0      1      0  71.2833         0   38
2            3      one       3    0      0      0   7.9250         2   26
3            4      one       1    0      1      0  53.1000         2   35
4            5        1       3    1      0      0   8.0500         2   35

In [163]:
train.loc[train["Survived"]=="one","Survived"]= 0

In [164]:
train.head()

PassengerId Survived  Pclass  Sex  SibSp  Parch     Fare  Embarked  Age
0            1        1       3    1      1      0   7.2500         2   22
1            2        0       1    0      1      0  71.2833         0   38
2            3        0       3    0      0      0   7.9250         2   26
3            4        0       1    0      1      0  53.1000         2   35
4            5        1       3    1      0      0   8.0500         2   35

In [165]:
df.head()

PassengerId  Survived  Pclass  Sex  SibSp  Parch     Fare  Embarked  Age
0            1         0       3    1      1      0   7.2500         2   22
1            2         1       1    0      1      0  71.2833         0   38
2            3         1       3    0      0      0   7.9250         2   26
3            4         1       1    0      1      0  53.1000         2   35
4            5         0       3    1      0      0   8.0500         2   35

In [166]:
feature=["Pclass","Sex","SibSp","Parch","Fare","Embarked","Age"]

In [167]:
X_train=train.loc[:,feature]
X_test = test.loc[:,feature]
y_train=train.loc[:,["Survived"]] #class label
y_test = test.loc[:,["Survived"]]
y_train=y_train.astype(int)


In [168]:
#X=org1.loc[:,["Pclass","Sex","SibSp","Parch","Fare","Embarked","Age"]]
#y=org1.loc[:,["Survived"]] #class label
#y=y.astype(int)

In [169]:
#X_train, X_test, y_train, y_test= train_test_split(X,y,random_state=0,train_size=0.6)

In [170]:
bn = BernoulliNB()
bn.fit(X_train, y_train.values.ravel()) #  fitting bnb to the training set
y_pred=bn.predict(X_test)

In [171]:
y_pred

array([0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       1, 1])

In [172]:
original_pred

array([1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 0], dtype=int64)

In [173]:
#y_test

In [174]:
#ac_ap=accuracy_score(y_test,y_pred)
#ac_ap

In [175]:
# The new accuracy is similar to the original one

In [176]:
original_pred[0]==y_pred[0]

False

In [177]:
original_pred

array([1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 0], dtype=int64)

In [178]:
ones=0
zeros=0
other=0
for x in range(0,200):
    
    if original_pred[x]==1 and y_pred[x]==1:
        ones+=1
    elif original_pred[x]==0 and y_pred[x]==0:
        zeros+=1
    else:
        other+=1
print(ones,zeros,other)

0 0 200


In [179]:
oness=0
zeross=0
for x in range(len(original_pred)):
    if original_pred[x]==1:
        oness+=1
    else:
        zeross+=1
print(oness,zeross)

66 134


In [180]:
print(f"The number of ones that have changed to zeros are {oness-ones}")
print(f"The number of zeros that have changed to ones are {zeross-zeros}")

The number of ones that have changed to zeros are 66
The number of zeros that have changed to ones are 134


# MR 0 Applying Transformations

In [181]:
df.head()

PassengerId  Survived  Pclass  Sex  SibSp  Parch     Fare  Embarked  Age
0            1         0       3    1      1      0   7.2500         2   22
1            2         1       1    0      1      0  71.2833         0   38
2            3         1       3    0      0      0   7.9250         2   26
3            4         1       1    0      1      0  53.1000         2   35
4            5         0       3    1      0      0   8.0500         2   35

In [182]:
att=df.copy()

In [183]:
train=att[:691].copy()
test=att[691:].copy()

In [184]:
train["Age"]=(train["Age"] * 2) + 1 #k(x) + b where k=2 and b=1
test["Age"]=(test["Age"]*2) + 1

In [185]:
att.copy()

PassengerId  Survived  Pclass  Sex  SibSp  Parch     Fare  Embarked  Age
0              1         0       3    1      1      0   7.2500         2   22
1              2         1       1    0      1      0  71.2833         0   38
2              3         1       3    0      0      0   7.9250         2   26
3              4         1       1    0      1      0  53.1000         2   35
4              5         0       3    1      0      0   8.0500         2   35
..           ...       ...     ...  ...    ...    ...      ...       ...  ...
886          887         0       2    1      0      0  13.0000         2   27
887          888         1       1    0      0      0  30.0000         2   19
888          889         0       3    0      1      2  23.4500         2   15
889          890         1       1    1      0      0  30.0000         0   26
890          891         0       3    1      0      0   7.7500         1   32

[891 rows x 9 columns]

In [186]:
train["Fare"]= (train["Fare"] * 2) + 1
test["Fare"]= (test["Fare"] * 2) + 1

In [187]:
att.copy()

PassengerId  Survived  Pclass  Sex  SibSp  Parch     Fare  Embarked  Age
0              1         0       3    1      1      0   7.2500         2   22
1              2         1       1    0      1      0  71.2833         0   38
2              3         1       3    0      0      0   7.9250         2   26
3              4         1       1    0      1      0  53.1000         2   35
4              5         0       3    1      0      0   8.0500         2   35
..           ...       ...     ...  ...    ...    ...      ...       ...  ...
886          887         0       2    1      0      0  13.0000         2   27
887          888         1       1    0      0      0  30.0000         2   19
888          889         0       3    0      1      2  23.4500         2   15
889          890         1       1    1      0      0  30.0000         0   26
890          891         0       3    1      0      0   7.7500         1   32

[891 rows x 9 columns]

In [188]:
feature=["Pclass","Sex","SibSp","Parch","Fare","Embarked","Age"]

In [189]:
X_train=train.loc[:,feature]
X_test = test.loc[:,feature]
y_train=train.loc[:,["Survived"]] #class label
y_test = test.loc[:,["Survived"]]
y_train=y_train.astype(int)

In [190]:
bn = BernoulliNB()
bn.fit(X_train, y_train.values.ravel()) #  fitting bnb to the training set
y_pred=bn.predict(X_test)

In [191]:
y_pred

array([1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 0])

In [192]:
y_test

Survived
691         1
692         1
693         0
694         0
695         0
..        ...
886         0
887         1
888         0
889         1
890         0

[200 rows x 1 columns]

In [193]:
y_test.index

RangeIndex(start=691, stop=891, step=1)

In [194]:
ap_acc = accuracy_score(y_test,y_pred)
ap_acc

0.795

In [195]:
original_pred

array([1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 0], dtype=int64)

In [196]:
original_test.index

RangeIndex(start=691, stop=891, step=1)

In [197]:
len(original_pred)

200

In [198]:
ones=0
zeros=0
other=0
for x in range(0,200):
    
    if original_pred[x]==1 and y_pred[x]==1:
        ones+=1
    elif original_pred[x]==0 and y_pred[x]==0:
        zeros+=1
    else:
        other+=1
print(ones,zeros,other)

65 134 1


In [199]:
oness=0
zeross=0
for x in range(len(original_pred)):
    if original_pred[x]==1:
        oness+=1
    else:
        zeross+=1
print(oness,zeross)

66 134


In [200]:
print(f"The number of ones that have changed to zeros are {oness-ones}")
print(f"The number of zeros that have changed to ones are {zeross-zeros}")


The number of ones that have changed to zeros are 1
The number of zeros that have changed to ones are 0


# 3.1 Add a particular index and its data to the original dataset and apply the model...that particular index value shouldn't change

# repeat this for other labels as well dont have to compare at the end 

# repeat this for random labels

In [201]:
original_pred

array([1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 0], dtype=int64)

In [202]:
original_test

Survived
691         1
692         1
693         0
694         0
695         0
..        ...
886         0
887         1
888         0
889         1
890         0

[200 rows x 1 columns]

In [203]:
train=df[:691].copy()
test=df[691:].copy()

In [204]:
b=test[0:1].copy()

In [205]:
b["Survived"]=1
#b.loc[0:1,"Survived"]=1

In [206]:
b

PassengerId  Survived  Pclass  Sex  SibSp  Parch     Fare  Embarked  Age
691          692         1       3    0      0      1  13.4167         0    4

In [207]:
c=pd.concat([train,b],axis=0)

In [208]:
c.head()

PassengerId  Survived  Pclass  Sex  SibSp  Parch     Fare  Embarked  Age
0            1         0       3    1      1      0   7.2500         2   22
1            2         1       1    0      1      0  71.2833         0   38
2            3         1       3    0      0      0   7.9250         2   26
3            4         1       1    0      1      0  53.1000         2   35
4            5         0       3    1      0      0   8.0500         2   35

In [209]:
c.shape

(692, 9)

In [210]:
c.tail()

PassengerId  Survived  Pclass  Sex  SibSp  Parch      Fare  Embarked  Age
687          688         0       3    1      0      0   10.1708         2   19
688          689         0       3    1      0      0    7.7958         2   18
689          690         1       1    0      0      1  211.3375         2   15
690          691         1       1    1      1      0   57.0000         2   31
691          692         1       3    0      0      1   13.4167         0    4

In [211]:
features=["Pclass","Sex","SibSp","Parch","Fare","Embarked","Age"]

In [212]:
X_train=c.loc[:,feature]
X_test = test.loc[:,feature]
y_train=c.loc[:,["Survived"]] #class label
y_test = test.loc[:,["Survived"]]
y_train=y_train.astype(int)

In [213]:
#X_train, X_test, y_train, y_test= train_test_split(X,y,random_state=0,train_size=0.6)

In [214]:
bn = BernoulliNB()
bn.fit(X_train, y_train.values.ravel()) #  fitting bnb to the training set
y_pred=bn.predict(X_test)

In [215]:
y_pred

array([1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 0])

In [216]:
y_pred[0]==original_pred[0]

True

In [217]:
d=test[1:2].copy()

In [218]:
d

PassengerId  Survived  Pclass  Sex  SibSp  Parch     Fare  Embarked  Age
692          693         1       3    1      0      0  56.4958         2   36

In [219]:
original_pred[1]

0

In [220]:
original_pred

array([1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 0], dtype=int64)

In [221]:
c=pd.concat([train,d],axis=0)

In [222]:
c.head()

PassengerId  Survived  Pclass  Sex  SibSp  Parch     Fare  Embarked  Age
0            1         0       3    1      1      0   7.2500         2   22
1            2         1       1    0      1      0  71.2833         0   38
2            3         1       3    0      0      0   7.9250         2   26
3            4         1       1    0      1      0  53.1000         2   35
4            5         0       3    1      0      0   8.0500         2   35

In [223]:
c.shape


(692, 9)

In [224]:
features=["Pclass","Sex","SibSp","Parch","Fare","Embarked","Age"]

In [225]:
X_train=c.loc[:,feature]
X_test = test.loc[:,feature]
y_train=c.loc[:,["Survived"]] #class label
y_test = test.loc[:,["Survived"]]
y_train=y_train.astype(int)

In [226]:
bn = BernoulliNB()
bn.fit(X_train, y_train.values.ravel()) #  fitting bnb to the training set
y_pred=bn.predict(X_test)

In [227]:
y_pred[1]==original_pred[1]

True

# 5.2  remove few subsets with a particular class value in this case survived  = , remove them from the training data set(but store its value). Now apply model the training dataset and apply that very same model on the removed subset, it's values should be similar to the stored values

# perform this operation on the traning set before splitting for both the values

In [228]:
df.copy()

PassengerId  Survived  Pclass  Sex  SibSp  Parch     Fare  Embarked  Age
0              1         0       3    1      1      0   7.2500         2   22
1              2         1       1    0      1      0  71.2833         0   38
2              3         1       3    0      0      0   7.9250         2   26
3              4         1       1    0      1      0  53.1000         2   35
4              5         0       3    1      0      0   8.0500         2   35
..           ...       ...     ...  ...    ...    ...      ...       ...  ...
886          887         0       2    1      0      0  13.0000         2   27
887          888         1       1    0      0      0  30.0000         2   19
888          889         0       3    0      1      2  23.4500         2   15
889          890         1       1    1      0      0  30.0000         0   26
890          891         0       3    1      0      0   7.7500         1   32

[891 rows x 9 columns]

In [229]:
train

PassengerId  Survived  Pclass  Sex  SibSp  Parch      Fare  Embarked  Age
0              1         0       3    1      1      0    7.2500         2   22
1              2         1       1    0      1      0   71.2833         0   38
2              3         1       3    0      0      0    7.9250         2   26
3              4         1       1    0      1      0   53.1000         2   35
4              5         0       3    1      0      0    8.0500         2   35
..           ...       ...     ...  ...    ...    ...       ...       ...  ...
686          687         0       3    1      4      1   39.6875         2   14
687          688         0       3    1      0      0   10.1708         2   19
688          689         0       3    1      0      0    7.7958         2   18
689          690         1       1    0      0      1  211.3375         2   15
690          691         1       1    1      1      0   57.0000         2   31

[691 rows x 9 columns]

In [230]:
rem=train[train["Survived"]==0]

In [231]:
rem

PassengerId  Survived  Pclass  Sex  SibSp  Parch     Fare  Embarked  Age
0              1         0       3    1      1      0   7.2500         2   22
4              5         0       3    1      0      0   8.0500         2   35
5              6         0       3    1      0      0   8.4583         1   28
6              7         0       1    1      0      0  51.8625         2   54
7              8         0       3    1      3      1  21.0750         2    2
..           ...       ...     ...  ...    ...    ...      ...       ...  ...
684          685         0       2    1      1      1  39.0000         2   60
685          686         0       2    1      1      2  41.5792         0   25
686          687         0       3    1      4      1  39.6875         2   14
687          688         0       3    1      0      0  10.1708         2   19
688          689         0       3    1      0      0   7.7958         2   18

[423 rows x 9 columns]

In [232]:
rem.index

Int64Index([  0,   4,   5,   6,   7,  12,  13,  14,  16,  18,
            ...
            676, 678, 680, 682, 683, 684, 685, 686, 687, 688],
           dtype='int64', length=423)

In [233]:
jk=train.copy()

In [234]:
# we will remove few samples of zero ie 0,4,5,6,7,12,13,14,16,18

In [235]:
jk.drop([0,4,5,6,7,12,13,14,16,18],axis=0,inplace=True)

In [236]:
jk.head()

PassengerId  Survived  Pclass  Sex  SibSp  Parch     Fare  Embarked  Age
1            2         1       1    0      1      0  71.2833         0   38
2            3         1       3    0      0      0   7.9250         2   26
3            4         1       1    0      1      0  53.1000         2   35
8            9         1       3    0      0      2  11.1333         2   27
9           10         1       2    0      1      0  30.0708         0   14

In [237]:
jk.tail()

PassengerId  Survived  Pclass  Sex  SibSp  Parch      Fare  Embarked  Age
686          687         0       3    1      4      1   39.6875         2   14
687          688         0       3    1      0      0   10.1708         2   19
688          689         0       3    1      0      0    7.7958         2   18
689          690         1       1    0      0      1  211.3375         2   15
690          691         1       1    1      1      0   57.0000         2   31

In [238]:
jk.shape

(681, 9)

In [239]:
# we have deleted 10 rows whose class labels aren't 1

In [240]:
test

PassengerId  Survived  Pclass  Sex  SibSp  Parch     Fare  Embarked  Age
691          692         1       3    0      0      1  13.4167         0    4
692          693         1       3    1      0      0  56.4958         2   36
693          694         0       3    1      0      0   7.2250         0   25
694          695         0       1    1      0      0  26.5500         2   60
695          696         0       2    1      0      0  13.5000         2   52
..           ...       ...     ...  ...    ...    ...      ...       ...  ...
886          887         0       2    1      0      0  13.0000         2   27
887          888         1       1    0      0      0  30.0000         2   19
888          889         0       3    0      1      2  23.4500         2   15
889          890         1       1    1      0      0  30.0000         0   26
890          891         0       3    1      0      0   7.7500         1   32

[200 rows x 9 columns]

In [241]:
features=["Pclass","Sex","SibSp","Parch","Fare","Embarked","Age"]

In [242]:
X_train=jk.loc[:,feature]
X_test = test.loc[:,feature]
y_train=jk.loc[:,["Survived"]] #class label
y_test = test.loc[:,["Survived"]]
y_train=y_train.astype(int)

In [243]:
#X_train, X_test, y_train, y_test= train_test_split(X,y,random_state=0,train_size=0.6)

In [244]:
bn = BernoulliNB()
bn.fit(X_train, y_train.values.ravel()) #  fitting bnb to the training set
y_pred=bn.predict(X_test)

In [245]:
y_pred

array([1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 0])

In [246]:
original_pred

array([1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 0], dtype=int64)

In [247]:
accuracy_score(y_test,y_pred)

0.81

In [248]:
y_pred.shape

(200,)

In [249]:
original_pred.shape

(200,)

In [250]:
ones=0
zeros=0
other=0
for x in range(0,200):
    
    if original_pred[x]==1 and y_pred[x]==1:
        ones+=1
    elif original_pred[x]==0 and y_pred[x]==0:
        zeros+=1
    else:
        other+=1
print(ones,zeros,other)

66 132 2


In [251]:
oness=0
zeross=0
for x in range(len(original_pred)):
    if original_pred[x]==1:
        oness+=1
    else:
        zeross+=1
print(oness,zeross)

66 134


In [252]:
print(f"The number of ones that have changed to zeros are {oness-ones}")
print(f"The number of zeros that have changed to ones are {zeross-zeros}")


The number of ones that have changed to zeros are 0
The number of zeros that have changed to ones are 2


# Checking for the other label ie 0, we will delete some labels whose values are 1

In [253]:
train

PassengerId  Survived  Pclass  Sex  SibSp  Parch      Fare  Embarked  Age
0              1         0       3    1      1      0    7.2500         2   22
1              2         1       1    0      1      0   71.2833         0   38
2              3         1       3    0      0      0    7.9250         2   26
3              4         1       1    0      1      0   53.1000         2   35
4              5         0       3    1      0      0    8.0500         2   35
..           ...       ...     ...  ...    ...    ...       ...       ...  ...
686          687         0       3    1      4      1   39.6875         2   14
687          688         0       3    1      0      0   10.1708         2   19
688          689         0       3    1      0      0    7.7958         2   18
689          690         1       1    0      0      1  211.3375         2   15
690          691         1       1    1      1      0   57.0000         2   31

[691 rows x 9 columns]

In [254]:
rem=train[train["Survived"]==1]

In [255]:
rem

PassengerId  Survived  Pclass  Sex  SibSp  Parch      Fare  Embarked  Age
1              2         1       1    0      1      0   71.2833         0   38
2              3         1       3    0      0      0    7.9250         2   26
3              4         1       1    0      1      0   53.1000         2   35
8              9         1       3    0      0      2   11.1333         2   27
9             10         1       2    0      1      0   30.0708         0   14
..           ...       ...     ...  ...    ...    ...       ...       ...  ...
677          678         1       3    0      0      0    9.8417         2   18
679          680         1       1    1      0      1  512.3292         0   36
681          682         1       1    1      0      0   76.7292         0   27
689          690         1       1    0      0      1  211.3375         2   15
690          691         1       1    1      1      0   57.0000         2   31

[268 rows x 9 columns]

In [256]:
rem.index

Int64Index([  1,   2,   3,   8,   9,  10,  11,  15,  17,  19,
            ...
            660, 664, 669, 670, 673, 677, 679, 681, 689, 690],
           dtype='int64', length=268)

In [257]:
jk=train.copy()

In [258]:
jk.drop([1,2,3,8,9,10,11,15,17,19],axis=0,inplace=True)

In [259]:
jk.head()

PassengerId  Survived  Pclass  Sex  SibSp  Parch     Fare  Embarked  Age
0            1         0       3    1      1      0   7.2500         2   22
4            5         0       3    1      0      0   8.0500         2   35
5            6         0       3    1      0      0   8.4583         1   28
6            7         0       1    1      0      0  51.8625         2   54
7            8         0       3    1      3      1  21.0750         2    2

In [260]:
jk.tail()

PassengerId  Survived  Pclass  Sex  SibSp  Parch      Fare  Embarked  Age
686          687         0       3    1      4      1   39.6875         2   14
687          688         0       3    1      0      0   10.1708         2   19
688          689         0       3    1      0      0    7.7958         2   18
689          690         1       1    0      0      1  211.3375         2   15
690          691         1       1    1      1      0   57.0000         2   31

In [261]:
test

PassengerId  Survived  Pclass  Sex  SibSp  Parch     Fare  Embarked  Age
691          692         1       3    0      0      1  13.4167         0    4
692          693         1       3    1      0      0  56.4958         2   36
693          694         0       3    1      0      0   7.2250         0   25
694          695         0       1    1      0      0  26.5500         2   60
695          696         0       2    1      0      0  13.5000         2   52
..           ...       ...     ...  ...    ...    ...      ...       ...  ...
886          887         0       2    1      0      0  13.0000         2   27
887          888         1       1    0      0      0  30.0000         2   19
888          889         0       3    0      1      2  23.4500         2   15
889          890         1       1    1      0      0  30.0000         0   26
890          891         0       3    1      0      0   7.7500         1   32

[200 rows x 9 columns]

In [262]:
features=["Pclass","Sex","SibSp","Parch","Fare","Embarked","Age"]

In [263]:
X_train=jk.loc[:,feature]
X_test = test.loc[:,feature]
y_train=jk.loc[:,["Survived"]] #class label
y_test = test.loc[:,["Survived"]]
y_train=y_train.astype(int)

In [264]:
bn = BernoulliNB()
bn.fit(X_train, y_train.values.ravel()) #  fitting bnb to the training set
y_pred=bn.predict(X_test)

In [265]:
y_pred

array([1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 0])

In [266]:
original_pred

array([1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 0], dtype=int64)

In [267]:
ones=0
zeros=0
other=0
for x in range(0,200):
    
    if original_pred[x]==1 and y_pred[x]==1:
        ones+=1
    elif original_pred[x]==0 and y_pred[x]==0:
        zeros+=1
    else:
        other+=1
print(ones,zeros,other)

66 134 0


In [268]:
oness=0
zeross=0
for x in range(len(original_pred)):
    if original_pred[x]==1:
        oness+=1
    else:
        zeross+=1
print(oness,zeross)

66 134


In [269]:
print(f"The number of ones that have changed to zeros are {oness-ones}")
print(f"The number of zeros that have changed to ones are {zeross-zeros}")

The number of ones that have changed to zeros are 0
The number of zeros that have changed to ones are 0
